USE ROLE ACCOUNTADMIN;

DROP ROLE IF EXISTS LOADER;
DROP ROLE IF EXISTS TRANSFORMER;
DROP ROLE IF EXISTS REPORTER;

DROP ROLE IF EXISTS LOADER_DEV;
DROP ROLE IF EXISTS TRANSFORMER_DEV;
DROP ROLE IF EXISTS REPORTER_DEV;

DROP ROLE IF EXISTS LOADER_PREPROD;
DROP ROLE IF EXISTS TRANSFORMER_PREPROD;
DROP ROLE IF EXISTS REPORTER_PREPROD;

DROP DATABASE IF EXISTS RAW CASCADE;
DROP DATABASE IF EXISTS ANALYTICS CASCADE;

DROP DATABASE IF EXISTS RAW_DEV CASCADE;
DROP DATABASE IF EXISTS ANALYTICS_DEV CASCADE;

DROP DATABASE IF EXISTS RAW_PREPROD CASCADE;
DROP DATABASE IF EXISTS ANALYTICS_PREPROD CASCADE;

DROP WAREHOUSE IF EXISTS LOADING;
DROP WAREHOUSE IF EXISTS TRANSFORMING;
DROP WAREHOUSE IF EXISTS REPORTING;

DROP WAREHOUSE IF EXISTS LOADING_DEV;
DROP WAREHOUSE IF EXISTS TRANSFORMING_DEV;
DROP WAREHOUSE IF EXISTS REPORTING_DEV;

DROP WAREHOUSE IF EXISTS LOADING_PREPROD;
DROP WAREHOUSE IF EXISTS TRANSFORMING_PREPROD;
DROP WAREHOUSE IF EXISTS REPORTING_PREPROD;

-- Creating databases
CREATE DATABASE RAW COMMENT = 'Production landing zone for raw data';
CREATE DATABASE ANALYTICS COMMENT = 'Production data layer for analytics';
CREATE DATABASE RAW_DEV CLONE RAW COMMENT = 'Development landing zone for raw data';
CREATE DATABASE ANALYTICS_DEV CLONE ANALYTICS COMMENT = 'Development data layer for analytics';
CREATE DATABASE RAW_PREPROD CLONE RAW COMMENT = 'QA landing zone for raw data';
CREATE DATABASE ANALYTICS_PREPROD CLONE ANALYTICS COMMENT = 'QA data layer for analytics';

-- Creating warehouses
CREATE WAREHOUSE LOADING WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE COMMENT = 'Production warehouse for data loading';
CREATE WAREHOUSE TRANSFORMING WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE COMMENT = 'Production warehouse for data transformation';
CREATE WAREHOUSE REPORTING WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE COMMENT = 'Production warehouse for BI and reporting';

CREATE WAREHOUSE LOADING_DEV WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE COMMENT = 'Development warehouse for data loading';
CREATE WAREHOUSE TRANSFORMING_DEV WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE COMMENT = 'Development warehouse for data transformation';
CREATE WAREHOUSE REPORTING_DEV WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE COMMENT = 'Development warehouse for BI and reporting';

CREATE WAREHOUSE LOADING_PREPROD WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE COMMENT = 'QA warehouse for data loading';
CREATE WAREHOUSE TRANSFORMING_PREPROD WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE COMMENT = 'QA warehouse for data transformation';
CREATE WAREHOUSE REPORTING_PREPROD WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE COMMENT = 'QA warehouse for BI and reporting';

-- Creating roles for each environment
CREATE ROLE LOADER COMMENT = 'Role for production data ingestion';
CREATE ROLE TRANSFORMER COMMENT = 'Role for production data transformations';
CREATE ROLE REPORTER COMMENT = 'Role for production BI tools and data consumers';

CREATE ROLE LOADER_DEV COMMENT = 'Role for development data ingestion';
CREATE ROLE TRANSFORMER_DEV COMMENT = 'Role for development data transformations';
CREATE ROLE REPORTER_DEV COMMENT = 'Role for development BI tools and data consumers';

CREATE ROLE LOADER_PREPROD COMMENT = 'Role for QA data ingestion';
CREATE ROLE TRANSFORMER_PREPROD COMMENT = 'Role for QA data transformations';
CREATE ROLE REPORTER_PREPROD COMMENT = 'Role for QA BI tools and data consumers';

-- Granting permissions for production LOADER role
GRANT USAGE, OPERATE ON WAREHOUSE LOADING TO ROLE LOADER;
GRANT ALL ON DATABASE RAW TO ROLE LOADER;
GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE RAW TO ROLE LOADER;
GRANT CREATE TABLE ON FUTURE SCHEMAS IN DATABASE RAW TO ROLE LOADER;
GRANT MONITOR USAGE ON ACCOUNT TO ROLE LOADER;


-- Granting permissions for production TRANSFORMER role
GRANT USAGE, OPERATE ON WAREHOUSE TRANSFORMING TO ROLE TRANSFORMER;
GRANT USAGE ON DATABASE RAW TO ROLE TRANSFORMER;
GRANT ALL ON DATABASE ANALYTICS TO ROLE TRANSFORMER;
GRANT SELECT ON ALL TABLES IN DATABASE RAW TO ROLE TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN DATABASE RAW TO ROLE TRANSFORMER;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RAW_DEV TO ROLE TRANSFORMER;

-- Granting permissions for production REPORTER role
GRANT USAGE, OPERATE ON WAREHOUSE REPORTING TO ROLE REPORTER;
GRANT USAGE ON DATABASE ANALYTICS TO ROLE REPORTER;
GRANT SELECT ON ALL TABLES IN DATABASE ANALYTICS TO ROLE REPORTER;
GRANT SELECT ON FUTURE TABLES IN DATABASE ANALYTICS TO ROLE REPORTER;

-- Granting permissions for development LOADER role
GRANT USAGE, OPERATE ON WAREHOUSE LOADING_DEV TO ROLE LOADER_DEV;
GRANT ALL ON DATABASE RAW_DEV TO ROLE LOADER_DEV;
GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE RAW_DEV TO ROLE LOADER_DEV;
GRANT CREATE TABLE ON FUTURE SCHEMAS IN DATABASE RAW_DEV TO ROLE LOADER_DEV;
GRANT MONITOR USAGE ON ACCOUNT TO ROLE LOADER_DEV;


-- Granting permissions for development TRANSFORMER role
GRANT USAGE, OPERATE ON WAREHOUSE TRANSFORMING_DEV TO ROLE TRANSFORMER_DEV;
GRANT USAGE ON DATABASE RAW_DEV TO ROLE TRANSFORMER_DEV;
GRANT ALL ON DATABASE ANALYTICS_DEV TO ROLE TRANSFORMER_DEV;
GRANT SELECT ON ALL TABLES IN DATABASE RAW_DEV TO ROLE TRANSFORMER_DEV;
GRANT SELECT ON FUTURE TABLES IN DATABASE RAW_DEV TO ROLE TRANSFORMER_DEV;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RAW_DEV TO ROLE TRANSFORMER_DEV;

-- Granting permissions for development REPORTER role
GRANT USAGE, OPERATE ON WAREHOUSE REPORTING_DEV TO ROLE REPORTER_DEV;
GRANT USAGE ON DATABASE ANALYTICS_DEV TO ROLE REPORTER_DEV;
GRANT SELECT ON ALL TABLES IN DATABASE ANALYTICS_DEV TO ROLE REPORTER_DEV;
GRANT SELECT ON FUTURE TABLES IN DATABASE ANALYTICS_DEV TO ROLE REPORTER_DEV;

-- Granting permissions for QA LOADER role
GRANT USAGE, OPERATE ON WAREHOUSE LOADING_PREPROD TO ROLE LOADER_PREPROD;
GRANT ALL ON DATABASE RAW_DEV TO ROLE LOADER_PREPROD;
GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE RAW_PREPROD TO ROLE LOADER_PREPROD;
GRANT CREATE TABLE ON FUTURE SCHEMAS IN DATABASE RAW_PREPROD TO ROLE LOADER_PREPROD;
GRANT MONITOR USAGE ON ACCOUNT TO ROLE LOADER_PREPROD;


-- Granting permissions for QA TRANSFORMER role
GRANT USAGE, OPERATE ON WAREHOUSE TRANSFORMING_PREPROD TO ROLE TRANSFORMER_PREPROD;
GRANT USAGE ON DATABASE RAW_PREPROD TO ROLE TRANSFORMER_PREPROD;
GRANT ALL ON DATABASE ANALYTICS_PREPROD TO ROLE TRANSFORMER_PREPROD;
GRANT SELECT ON ALL TABLES IN DATABASE RAW_PREPROD TO ROLE TRANSFORMER_PREPROD;
GRANT SELECT ON FUTURE TABLES IN DATABASE RAW_PREPROD TO ROLE TRANSFORMER_PREPROD;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RAW_DEV TO ROLE TRANSFORMER_PREPROD;

-- Granting permissions for QA REPORTER role
GRANT USAGE, OPERATE ON WAREHOUSE REPORTING_PREPROD TO ROLE REPORTER_PREPROD;
GRANT USAGE ON DATABASE ANALYTICS_PREPROD TO ROLE REPORTER_PREPROD;
GRANT SELECT ON ALL TABLES IN DATABASE ANALYTICS_PREPROD TO ROLE REPORTER_PREPROD;
GRANT SELECT ON FUTURE TABLES IN DATABASE ANALYTICS_PREPROD TO ROLE REPORTER_PREPROD;
