CREATE OR REPLACE USER dbt_shrestic PASSWORD='password';
GRANT ROLE TRANSFORMER_DEV TO USER dbt_shrestic;


CREATE OR REPLACE USER loader_adam PASSWORD='password';
GRANT ROLE LOADER_DEV TO USER loader_adam;
GRANT USAGE ON INTEGRATION S3_INT TO ROLE LOADER_DEV;


CREATE OR REPLACE USER CI_USER PASSWORD = 'password';
CREATE OR REPLACE ROLE CI_ROLE COMMENT = 'This role is use for CI/CD operations';
GRANT ROLE CI_ROLE TO USER CI_USER;

REVOKE APPLYBUDGET ON DATABASE ANALYTICS_PROD FROM ROLE TRANSFORMER_PROD;
GRANT OWNERSHIP ON DATABASE ANALYTICS_PROD TO ROLE CI_ROLE REVOKE CURRENT GRANTS;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE CI_ROLE;

REVOKE APPLYBUDGET ON DATABASE RAW_PROD FROM ROLE LOADER_PROD;
GRANT OWNERSHIP ON DATABASE RAW_PROD TO ROLE CI_ROLE REVOKE CURRENT GRANTS;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE CI_ROLE;

GRANT ROLE TRANSFORMER_DEV,TRANSFORMER_PREPROD,TRANSFORMER_PROD TO ROLE CI_ROLE;

SHOW GRANTS TO ROLE CI_ROLE;
