USE ROLE ACCOUNTADMIN;

-- Dropping existing objects for a fresh setup
DROP USER IF EXISTS LOADER_USER;
DROP USER IF EXISTS REPORTER_USER;
DROP USER IF EXISTS ANALYST_USER;
DROP USER IF EXISTS LOADER_USER_DEV;
DROP USER IF EXISTS REPORTER_USER_DEV;
DROP USER IF EXISTS ANALYST_USER_DEV;
DROP USER IF EXISTS LOADER_USER_QA;
DROP USER IF EXISTS REPORTER_USER_QA;
DROP USER IF EXISTS ANALYST_USER_QA;

DROP ROLE IF EXISTS LOADER;
DROP ROLE IF EXISTS TRANSFORMER;
DROP ROLE IF EXISTS REPORTER;
DROP ROLE IF EXISTS LOADER_DEV;
DROP ROLE IF EXISTS TRANSFORMER_DEV;
DROP ROLE IF EXISTS REPORTER_DEV;
DROP ROLE IF EXISTS LOADER_QA;
DROP ROLE IF EXISTS TRANSFORMER_QA;
DROP ROLE IF EXISTS REPORTER_QA;

DROP DATABASE IF EXISTS RAW CASCADE;
DROP DATABASE IF EXISTS ANALYTICS CASCADE;
DROP DATABASE IF EXISTS RAW_DEV CASCADE;
DROP DATABASE IF EXISTS ANALYTICS_DEV CASCADE;
DROP DATABASE IF EXISTS RAW_QA CASCADE;
DROP DATABASE IF EXISTS ANALYTICS_QA CASCADE;

DROP WAREHOUSE IF EXISTS LOADING;
DROP WAREHOUSE IF EXISTS TRANSFORMING;
DROP WAREHOUSE IF EXISTS REPORTING;
DROP WAREHOUSE IF EXISTS LOADING_DEV;
DROP WAREHOUSE IF EXISTS TRANSFORMING_DEV;
DROP WAREHOUSE IF EXISTS REPORTING_DEV;
DROP WAREHOUSE IF EXISTS LOADING_QA;
DROP WAREHOUSE IF EXISTS TRANSFORMING_QA;
DROP WAREHOUSE IF EXISTS REPORTING_QA;

-- Creating databases
CREATE DATABASE RAW COMMENT = 'Production landing zone for raw data';
CREATE DATABASE ANALYTICS COMMENT = 'Production data layer for analytics';
CREATE DATABASE RAW_DEV CLONE RAW COMMENT = 'Development landing zone for raw data';
CREATE DATABASE ANALYTICS_DEV CLONE ANALYTICS COMMENT = 'Development data layer for analytics';
CREATE DATABASE RAW_QA CLONE RAW COMMENT = 'QA landing zone for raw data';
CREATE DATABASE ANALYTICS_QA CLONE ANALYTICS COMMENT = 'QA data layer for analytics';

-- Creating warehouses
CREATE WAREHOUSE LOADING WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE COMMENT = 'Production warehouse for data loading';
CREATE WAREHOUSE TRANSFORMING WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE COMMENT = 'Production warehouse for data transformation';
CREATE WAREHOUSE REPORTING WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE COMMENT = 'Production warehouse for BI and reporting';

CREATE WAREHOUSE LOADING_DEV WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE COMMENT = 'Development warehouse for data loading';
CREATE WAREHOUSE TRANSFORMING_DEV WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE COMMENT = 'Development warehouse for data transformation';
CREATE WAREHOUSE REPORTING_DEV WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE COMMENT = 'Development warehouse for BI and reporting';

CREATE WAREHOUSE LOADING_QA WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE COMMENT = 'QA warehouse for data loading';
CREATE WAREHOUSE TRANSFORMING_QA WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE COMMENT = 'QA warehouse for data transformation';
CREATE WAREHOUSE REPORTING_QA WITH WAREHOUSE_SIZE = 'XSMALL' WAREHOUSE_TYPE = 'STANDARD' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE COMMENT = 'QA warehouse for BI and reporting';

-- Creating roles for each environment
CREATE ROLE LOADER COMMENT = 'Role for production data ingestion';
CREATE ROLE TRANSFORMER COMMENT = 'Role for production data transformations';
CREATE ROLE REPORTER COMMENT = 'Role for production BI tools and data consumers';

CREATE ROLE LOADER_DEV COMMENT = 'Role for development data ingestion';
CREATE ROLE TRANSFORMER_DEV COMMENT = 'Role for development data transformations';
CREATE ROLE REPORTER_DEV COMMENT = 'Role for development BI tools and data consumers';

CREATE ROLE LOADER_QA COMMENT = 'Role for QA data ingestion';
CREATE ROLE TRANSFORMER_QA COMMENT = 'Role for QA data transformations';
CREATE ROLE REPORTER_QA COMMENT = 'Role for QA BI tools and data consumers';

-- Granting permissions for production LOADER role
GRANT USAGE, OPERATE ON WAREHOUSE LOADING TO ROLE LOADER;
GRANT ALL ON DATABASE RAW TO ROLE LOADER;
GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE RAW TO ROLE LOADER;
GRANT CREATE TABLE ON FUTURE SCHEMAS IN DATABASE RAW TO ROLE LOADER;

-- Granting permissions for production TRANSFORMER role
GRANT USAGE, OPERATE ON WAREHOUSE TRANSFORMING TO ROLE TRANSFORMER;
GRANT USAGE ON DATABASE RAW TO ROLE TRANSFORMER;
GRANT ALL ON DATABASE ANALYTICS TO ROLE TRANSFORMER;
GRANT SELECT ON ALL TABLES IN DATABASE RAW TO ROLE TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN DATABASE RAW TO ROLE TRANSFORMER;

-- Granting permissions for production REPORTER role
GRANT USAGE, OPERATE ON WAREHOUSE REPORTING TO ROLE REPORTER;
GRANT USAGE ON DATABASE ANALYTICS TO ROLE REPORTER;
GRANT SELECT ON ALL TABLES IN DATABASE ANALYTICS TO ROLE REPORTER;
GRANT SELECT ON FUTURE TABLES IN DATABASE ANALYTICS TO ROLE REPORTER;

-- Granting permissions for development LOADER role
GRANT USAGE, OPERATE ON WAREHOUSE LOADING_DEV TO ROLE LOADER_DEV;
GRANT ALL ON DATABASE RAW_DEV TO ROLE LOADER_DEV;
GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE RAW_DEV TO ROLE LOADER_DEV;
GRANT CREATE TABLE ON FUTURE SCHEMAS IN DATABASE RAW_DEV TO ROLE LOADER_DEV;


-- Granting permissions for development TRANSFORMER role
GRANT USAGE, OPERATE ON WAREHOUSE TRANSFORMING_DEV TO ROLE TRANSFORMER_DEV;
GRANT USAGE ON DATABASE RAW_DEV TO ROLE TRANSFORMER_DEV;
GRANT ALL ON DATABASE ANALYTICS_DEV TO ROLE TRANSFORMER_DEV;
GRANT SELECT ON ALL TABLES IN DATABASE RAW_DEV TO ROLE TRANSFORMER_DEV;
GRANT SELECT ON FUTURE TABLES IN DATABASE RAW_DEV TO ROLE TRANSFORMER_DEV;

-- Granting permissions for development REPORTER role
GRANT USAGE, OPERATE ON WAREHOUSE REPORTING_DEV TO ROLE REPORTER_DEV;
GRANT USAGE ON DATABASE ANALYTICS_DEV TO ROLE REPORTER_DEV;
GRANT SELECT ON ALL TABLES IN DATABASE ANALYTICS_DEV TO ROLE REPORTER_DEV;
GRANT SELECT ON FUTURE TABLES IN DATABASE ANALYTICS_DEV TO ROLE REPORTER_DEV;

-- Granting permissions for QA LOADER role
GRANT USAGE, OPERATE ON WAREHOUSE LOADING_QA TO ROLE LOADER_QA;
GRANT ALL ON DATABASE RAW_DEV TO ROLE LOADER_QA;
GRANT CREATE TABLE ON ALL SCHEMAS IN DATABASE RAW_QA TO ROLE LOADER_QA;
GRANT CREATE TABLE ON FUTURE SCHEMAS IN DATABASE RAW_QA TO ROLE LOADER_QA;


-- Granting permissions for QA TRANSFORMER role
GRANT USAGE, OPERATE ON WAREHOUSE TRANSFORMING_QA TO ROLE TRANSFORMER_QA;
GRANT USAGE ON DATABASE RAW_QA TO ROLE TRANSFORMER_QA;
GRANT ALL ON DATABASE ANALYTICS_QA TO ROLE TRANSFORMER_QA;
GRANT SELECT ON ALL TABLES IN DATABASE RAW_QA TO ROLE TRANSFORMER_QA;
GRANT SELECT ON FUTURE TABLES IN DATABASE RAW_QA TO ROLE TRANSFORMER_QA;

-- Granting permissions for QA REPORTER role
GRANT USAGE, OPERATE ON WAREHOUSE REPORTING_QA TO ROLE REPORTER_QA;
GRANT USAGE ON DATABASE ANALYTICS_QA TO ROLE REPORTER_QA;
GRANT SELECT ON ALL TABLES IN DATABASE ANALYTICS_QA TO ROLE REPORTER_QA;
GRANT SELECT ON FUTURE TABLES IN DATABASE ANALYTICS_QA TO ROLE REPORTER_QA;

-- Creating users and associating with production roles
CREATE USER LOADER_USER PASSWORD = 'password' DEFAULT_ROLE = LOADER MUST_CHANGE_PASSWORD = TRUE;
GRANT ROLE LOADER TO USER LOADER_USER;

CREATE USER REPORTER_USER PASSWORD = 'password' DEFAULT_ROLE = REPORTER MUST_CHANGE_PASSWORD = TRUE;
GRANT ROLE REPORTER TO USER REPORTER_USER;

CREATE USER ANALYST_USER PASSWORD = 'password' DEFAULT_ROLE = REPORTER MUST_CHANGE_PASSWORD = TRUE;
GRANT ROLE REPORTER TO USER ANALYST_USER;

-- Creating users and associating with development roles
CREATE USER LOADER_USER_DEV PASSWORD = 'password' DEFAULT_ROLE = LOADER_DEV MUST_CHANGE_PASSWORD = TRUE;
GRANT ROLE LOADER_DEV TO USER LOADER_USER_DEV;

CREATE USER REPORTER_USER_DEV PASSWORD = 'password' DEFAULT_ROLE = REPORTER_DEV MUST_CHANGE_PASSWORD = TRUE;
GRANT ROLE REPORTER_DEV TO USER REPORTER_USER_DEV;

CREATE USER ANALYST_USER_DEV PASSWORD = 'password' DEFAULT_ROLE = REPORTER_DEV MUST_CHANGE_PASSWORD = TRUE;
GRANT ROLE REPORTER_DEV TO USER ANALYST_USER_DEV;

-- Creating users and associating with QA roles
CREATE USER LOADER_USER_QA PASSWORD = 'password' DEFAULT_ROLE = LOADER_QA MUST_CHANGE_PASSWORD = TRUE;
GRANT ROLE LOADER_QA TO USER LOADER_USER_QA;

CREATE USER REPORTER_USER_QA PASSWORD = 'password' DEFAULT_ROLE = REPORTER_QA MUST_CHANGE_PASSWORD = TRUE;
GRANT ROLE REPORTER_QA TO USER REPORTER_USER_QA;

CREATE USER ANALYST_USER_QA PASSWORD = 'password' DEFAULT_ROLE = REPORTER_QA MUST_CHANGE_PASSWORD = TRUE;
GRANT ROLE REPORTER_QA TO USER ANALYST_USER_QA;
