mainkode:
  outputs:
    dev:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: dumb
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: accountadmin
      schema: public
      threads: 4
      type: snowflake
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      warehouse: compute_wh
  target: dev
