from airflow.providers.cncf.kubernetes.secret import Secret

SNOWFLAKE_ACCOUNT = Secret("env", "SNOWFLAKE_ACCOUNT", "airflow", "SNOWFLAKE_ACCOUNT")
SNOWFLAKE_TRANSFORM_USER = Secret("env", "SNOWFLAKE_TRANSFORM_USER", "airflow", "SNOWFLAKE_TRANSFORM_USER")
SNOWFLAKE_TRANSFORM_PASSWORD = Secret("env", "SNOWFLAKE_TRANSFORM_PASSWORD", "airflow", "SNOWFLAKE_TRANSFORM_PASSWORD")
SNOWFLAKE_TRANSFORM_ROLE = Secret("env", "SNOWFLAKE_TRANSFORM_ROLE", 'airflow', "SNOWFLAKE_TRANSFORM_ROLE")
SNOWFLAKE_TRANSFORM_WAREHOUSE = Secret("env", "SNOWFLAKE_TRANSFORM_WAREHOUSE", 'airflow', "SNOWFLAKE_TRANSFORM_WAREHOUSE")
SNOWFLAKE_TRANSFORM_DATABASE = Secret("env", "SNOWFLAKE_TRANSFORM_DATABASE", 'airflow', "SNOWFLAKE_TRANSFORM_DATABASE")