mainkode:
  outputs:
    dev:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: "{{ env_var('SNOWFLAKE_TRANSFORM_DATABASE') }}"
      password: "{{ env_var('SNOWFLAKE_TRANSFORM_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_TRANSFORM_ROLE') }}"
      schema: "{{ env_var('SCHEMA_DBT_USERNAME') }}"
      threads: 4
      type: snowflake
      user: "{{ env_var('SNOWFLAKE_TRANSFORM_USER') }}"
      warehouse: "{{ env_var('SNOWFLAKE_TRANSFORM_WAREHOUSE') }}"
    qa:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: "{{ env_var('SNOWFLAKE_TRANSFORM_DATABASE') }}"
      password: "{{ env_var('SNOWFLAKE_TRANSFORM_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_TRANSFORM_ROLE') }}"
      schema: qa
      threads: 4
      type: snowflake
      user: "{{ env_var('SNOWFLAKE_TRANSFORM_USER') }}"
      warehouse: "{{ env_var('SNOWFLAKE_TRANSFORM_WAREHOUSE') }}"
    prod:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: "{{ env_var('SNOWFLAKE_TRANSFORM_DATABASE') }}"
      password: "{{ env_var('SNOWFLAKE_TRANSFORM_PASSWORD') }}"
      role: "{{ env_var('SNOWFLAKE_TRANSFORM_ROLE') }}"
      schema: prod
      threads: 4
      type: snowflake
      user: "{{ env_var('SNOWFLAKE_TRANSFORM_USER') }}"
      warehouse: "{{ env_var('SNOWFLAKE_TRANSFORM_WAREHOUSE') }}"
  target: dev
