name: dbt-slim

on:
  pull_request:
    branches:
      - qa
      - prod

  workflow_dispatch:
    inputs:
      developer:
        description: 'Select a dbt developer'
        required: true
        default: 'SHRESTIC'
        type: choice
        options:
          - SHRESTIC
          - SAM
          - TAYLOR
    

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-west-1
  DBT_PROFILES_DIR: ${{ github.workspace }}/transform/mainkode_analytics/profiles
  DBT_PROJECT_DIR: ${{ github.workspace }}/transform/mainkode_analytics
  DBT_ARTIFACT_PATH: s3://s3-dbt-artifacts/manifests/manifest.json
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_TRANSFORM_PASSWORD: ${{ secrets[format('DBT_PASS_{0}', github.event.inputs.developer)] }}
  SNOWFLAKE_TRANSFORM_USER: ${{ secrets[format('DBT_USER_{0}', github.event.inputs.developer)] }}
  SNOWFLAKE_TRANSFORM_DATABASE: ${{ vars.SNOWFLAKE_DATABASE }}
  SNOWFLAKE_TRANSFORM_ROLE: ${{ vars.SNOWFLAKE_ROLE }}
  SCHEMA_DBT_USERNAME: ${{ format('DBT_{0}', github.event.inputs.developer) }}
  SNOWFLAKE_TRANSFORM_WAREHOUSE: ${{ vars.SNOWFLAKE_WAREHOUSE }}
  BRANCH: ${{ vars.BRANCH }}
  TARGET_ENV: ${{ vars.TARGET_ENV }}


jobs:
  dbt-slim:
    runs-on: ubuntu-latest
    environment: ${{ github.base_ref == 'dev' && 'dev' || github.base_ref == 'qa' && 'qa' || 'prod' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::362262895301:role/github-action-s3
          aws-region: ${{ env.AWS_REGION }}

      - name: Download dbt manifest
        run: aws s3 cp ${{ env.DBT_ARTIFACT_PATH }} ${{ github.workspace }}

      - name: Install dbt dependencies
        run: |
          dbt deps --project-dir=transform/mainkode_analytics

      - name: Build modified dbt models and its first-order children
        run: |
          dbt build --profiles-dir=${{ env.DBT_PROFILES_DIR }} --project-dir=${{ env.DBT_PROJECT_DIR }} --target=${{ env.TARGET_ENV }} \
            --select state:modified+ --defer --state ${{ github.workspace }}

      - name: Lint dbt models
        run: |
          cd ${{ env.DBT_PROJECT_DIR }} && make lint-changed-new BRANCH=${{ env.BRANCH }}